language: java
env:
  global:
  - secure: GG+B5OjisD1wizc9kt9G363uoo6ZzkUJSsmdjWrQ3n1IHztRkAbGb9CstbUZ9AY3JgxkwrDVW85M1WCE1JaFPwXook/+tCNIxx41vZf3mIb7FFahv5M/yutnrfphPJwi+VqEIQL7deAT2plbxiuPbs88ydjQ2/TGA5BcYhz18Vs=
