sudo: required
language: java
jdk:
  - oraclejdk8
before_script:
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
script:
    - ./gradlew clean build
deploy:
    - ./gradlew distDocker
services:
  - docker
