sudo: required
language: java
jdk:
  - oraclejdk8
script:
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - ./gradlew clean build distDocker
    - docker tag albertonavarro/lazylogin:travis_"$TRAVIS_BUILD_NUMBER" albertonavarro/lazylogin:readytotest
    - docker push albertonavarro/lazylogin:readytotest
    - ./gradlew deploy_tools:waitUntilDeployed -P deploy_endpoint="$TEST_SERVER"/info -P deploy_expected_version=travis_"$TRAVIS_BUILD_NUMBER"
    - ./gradlew integration-test:test -Dlazylogin.url=$TEST_SERVER -Dtest.imap.username=$TEST_EMAIL_ACCOUNT -Dtest.imap.password=$TEST_EMAIL_PASSWORD -Dtest.imap.host=imap.gmail.com -PintegrationTests
    - docker tag albertonavarro/lazylogin:travis_"$TRAVIS_BUILD_NUMBER" albertonavarro/lazylogin:readyforprod
    - docker push albertonavarro/lazylogin:readyforprod
    - ./gradlew deploy_tools:waitUntilDeployed -P deploy_endpoint="$PROD_SERVER"/info -P deploy_expected_version=travis_"$TRAVIS_BUILD_NUMBER"
    - ./gradlew integration-test:test -Dlazylogin.url=$PROD_SERVER -Dtest.imap.username=$PROD_EMAIL_ACCOUNT -Dtest.imap.password=$PROD_EMAIL_PASSWORD -Dtest.imap.host=imap.gmail.com -PintegrationTests
services:
  - docker
