sudo: required
language: java
jdk:
  - oraclejdk8
script:
    - ./gradlew clean build
before_deploy:
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
deploy:
    - ./gradlew distDocker
services:
  - docker
