
default[:lazylogin][:email][:host] = "TO BE SET"
default[:lazylogin][:email][:port] = "TO BE SET"
default[:lazylogin][:email][:username] = "TO BE SET"
default[:lazylogin][:email][:password] = "TO BE SET"
default[:lazylogin][:email][:auth] = "TO BE SET"
default[:lazylogin][:email][:starttls_enable] = "TO BE SET"
default[:lazylogin][:email][:from] = "TO BE SET"
default[:lazylogin][:email][:subject] = "LazyLogin email verification"
default[:lazylogin][:email][:server_address] = "TO BE SET"

default[:lazylogin][:datasource][:host] = "TO BE SET"
default[:lazylogin][:datasource][:url] = "TO BE SET"
default[:lazylogin][:datasource][:username] = "TO BE SET"
default[:lazylogin][:datasource][:password] = "TO BE SET"
default[:lazylogin][:datasource][:driverClassName] = "TO BE SET"
default[:lazylogin][:datasource][:database] = "TO BE SET"
default[:lazylogin][:datasource][:generateDll] = "TO BE SET"
default[:lazylogin][:datasource][:dialect] = "TO BE SET"
default[:lazylogin][:datasource][:showSql] = "TO BE SET"
default[:lazylogin][:datasource][:testOnBorrow] = "TO BE SET"
default[:lazylogin][:datasource][:validationQuery] = "TO BE SET"

default[:lazylogin][:amq][:url] = "TO BE SET"

default[:lazylogin][:security][:keystore][:loc] = "TO BE SET"
default[:lazylogin][:security][:keystore][:password] = "TO BE SET"
default[:lazylogin][:security][:truststore][:loc] = "TO BE SET"
default[:lazylogin][:security][:truststore][:password] = "TO BE SET"
