#!/bin/sh
# chkconfig: 2345 95 20
# description: Some description
# What your script does (not sure if this is necessary though)
# processname: myscript
# Source function library.
. /etc/init.d/functions

pname="lazylogin"
exe="java -jar /root/springboot.war"
pidfile="/var/run/${pname}.pid"
lockfile="/var/lock/subsys/${pname}"
logfile="/var/log/lazylogin.log"
errfile="/var/log/lazylogin.err"

RETVAL=0

#[ -x $exe ] || exit 0

start() {
    echo -n "Starting $pname : "
    #daemon ${exe} # Not working ...
    if [ -s ${pidfile} ]; then
       RETVAL=1
       echo -n "Already running !" && warning
       echo
    else
       nohup ${exe} >>${logfile} 2>>${errfile} &
       RETVAL=$?
       PID=$!
       [ $RETVAL -eq 0 ] && touch ${lockfile} && success || failure
       echo
       echo $PID > ${pidfile}
    fi
}

stop() {
    echo -n "Shutting down $pname with PID `cat ${pidfile}`: "
    killproc -p ${pidfile}
    RETVAL=$?
    echo
    if [ $RETVAL -eq 0 ]; then
        rm -f ${lockfile}
        rm -f ${pidfile}
    fi
}

restart() {
    echo -n "Restarting $pname : "
    stop
    sleep 2
    start
}

case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    status)
        status ${pname}
    ;;
    restart)
        restart
    ;;
    *)
        echo "Usage: $0 {start|stop|status|restart}"
    ;; esac

exit 0